<a href="https://colab.research.google.com/github/Artificial-i/-1-5/blob/main/Vedio38_43_T5_Fasl4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive/')

Drive already mounted at /content/drive/; to attempt to forcibly remount, call drive.mount("/content/drive/", force_remount=True).


In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split, GridSearchCV,RandomizedSearchCV
from sklearn.metrics import accuracy_score,confusion_matrix,recall_score,precision_score,classification_report,confusion_matrix
from sklearn.ensemble import RandomForestClassifier
%matplotlib inline

In [ ]:
df=pd.read_csv('car_evaluation.csv')
df.head()


vhigh vhigh.1  2 2.1  small   low  unacc
0  vhigh   vhigh  2   2  small   med  unacc
1  vhigh   vhigh  2   2  small  high  unacc
2  vhigh   vhigh  2   2    med   low  unacc
3  vhigh   vhigh  2   2    med   med  unacc
4  vhigh   vhigh  2   2    med  high  unacc

In [ ]:
col_names = ['buying','maint','doors','persons','lug_boot','safety','class']
df.columns = col_names
df.head()

buying  maint doors persons lug_boot safety  class
0  vhigh  vhigh     2       2    small    med  unacc
1  vhigh  vhigh     2       2    small   high  unacc
2  vhigh  vhigh     2       2      med    low  unacc
3  vhigh  vhigh     2       2      med    med  unacc
4  vhigh  vhigh     2       2      med   high  unacc

In [ ]:
df.shape
df.columns
df.dtypes
df.info()
df.nunique()
df['buying'].value_counts()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1727 entries, 0 to 1726
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   buying    1727 non-null   object
 1   maint     1727 non-null   object
 2   doors     1727 non-null   object
 3   persons   1727 non-null   object
 4   lug_boot  1727 non-null   object
 5   safety    1727 non-null   object
 6   class     1727 non-null   object
dtypes: object(7)
memory usage: 94.6+ KB


buying      0
maint       0
doors       0
persons     0
lug_boot    0
safety      0
class       0
dtype: int64

In [ ]:
X = df.drop(['class'], axis=1)
y = df['class']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.33, random_state = 42)

In [ ]:
!pip install category_encoders

In [ ]:
import category_encoders as ce

ohe = ce.OneHotEncoder()
X_train_1 = ohe.fit_transform(X_train)
X_test_1 = ohe.transform(X_test)

oe = ce.OrdinalEncoder()
X_train_2 = oe.fit_transform(X_train)
X_test_2 = oe.transform(X_test)

be= ce.BinaryEncoder()
X_train_3 = be.fit_transform(X_train, y_train)
X_test_3 = be.transform(X_test)

/usr/local/lib/python3.11/dist-packages/sklearn/base.py:411: FutureWarning: The `_get_tags` method is deprecated in 1.6 and will be removed in 1.7. Please implement the `__sklearn_tags__` method.
  If False and the attribute exists, then check that it is equal to
/usr/local/lib/python3.11/dist-packages/sklearn/base.py:411: FutureWarning: The `_get_tags` method is deprecated in 1.6 and will be removed in 1.7. Please implement the `__sklearn_tags__` method.
  If False and the attribute exists, then check that it is equal to
/usr/local/lib/python3.11/dist-packages/sklearn/base.py:411: FutureWarning: The `_get_tags` method is deprecated in 1.6 and will be removed in 1.7. Please implement the `__sklearn_tags__` method.
  If False and the attribute exists, then check that it is equal to
/usr/local/lib/python3.11/dist-packages/sklearn/base.py:411: FutureWarning: The `_get_tags` method is deprecated in 1.6 and will be removed in 1.7. Please implement the `__sklearn_tags__` method.
  If False a

In [ ]:
import category_encoders as ce
oe = ce.OrdinalEncoder()
X_train = oe.fit_transform(X_train)
X_test = oe.transform(X_test)
X_train , X_test

/usr/local/lib/python3.11/dist-packages/sklearn/base.py:411: FutureWarning: The `_get_tags` method is deprecated in 1.6 and will be removed in 1.7. Please implement the `__sklearn_tags__` method.
  If False and the attribute exists, then check that it is equal to


(      buying  maint  doors  persons  lug_boot  safety
 83         1      1      1        1         1       1
 48         1      1      2        2         1       2
 468        2      1      2        3         2       2
 155        1      2      2        2         1       1
 1043       3      2      3        2         2       1
 ...      ...    ...    ...      ...       ...     ...
 1130       3      3      2        2         3       1
 1294       3      4      1        2         3       3
 860        2      4      1        2         3       1
 1459       4      2      3        1         2       3
 1126       3      3      2        2         2       3
 
 [1157 rows x 6 columns],
       buying  maint  doors  persons  lug_boot  safety
 599        2      2      3        1         3       1
 932        3      1      3        3         3       1
 628        2      2      1        1         3       3
 1497       4      2      1        3         1       2
 1262       3      4      3        2 

In [ ]:
rfc = RandomForestClassifier(random_state=0)
rfc.fit(X_train, y_train)
y_pred = rfc.predict(X_test)

print("confusion_matrix:\n",confusion_matrix(y_test, y_pred))
print("accuracy_score:", accuracy_score(y_test, y_pred))
print("recall_score:" , recall_score(y_test, y_pred,average='micro'))
print("precision_score:", precision_score(y_test, y_pred,average='micro'))
print(f"\nClassification Report:\n{classification_report(y_test, y_pred)}")

confusion_matrix:
 [[119   2   5   1]
 [  1  13   2   2]
 [  2   0 397   0]
 [  5   0   0  21]]
accuracy_score: 0.9649122807017544
recall_score: 0.9649122807017544
precision_score: 0.9649122807017544

Classification Report:
              precision    recall  f1-score   support

         acc       0.94      0.94      0.94       127
        good       0.87      0.72      0.79        18
       unacc       0.98      0.99      0.99       399
       vgood       0.88      0.81      0.84        26

    accuracy                           0.96       570
   macro avg       0.92      0.87      0.89       570
weighted avg       0.96      0.96      0.96       570



In [ ]:
rfc_100 = RandomForestClassifier(n_estimators=5, random_state=0)
rfc_100.fit(X_train, y_train)
y_pred_100 = rfc_100.predict(X_test)

print("confusion_matrix:\n", confusion_matrix(y_test, y_pred_100))
print("accuracy_score:", accuracy_score(y_test, y_pred_100))
print("recall_score:", recall_score(y_test, y_pred_100,average='micro'))
print("precision_score:", precision_score(y_test, y_pred_100,average='micro'))
print(f"\nClassification Report:\n{classification_report(y_test, y_pred_100)}")

confusion_matrix:
 [[110   6  11   0]
 [  2  11   2   3]
 [  8   0 391   0]
 [  5   4   1  16]]
accuracy_score: 0.9263157894736842
recall_score: 0.9263157894736842
precision_score: 0.9263157894736842

Classification Report:
              precision    recall  f1-score   support

         acc       0.88      0.87      0.87       127
        good       0.52      0.61      0.56        18
       unacc       0.97      0.98      0.97       399
       vgood       0.84      0.62      0.71        26

    accuracy                           0.93       570
   macro avg       0.80      0.77      0.78       570
weighted avg       0.93      0.93      0.93       570



In [ ]:
# برای مشخص کردن اهمیت هر کدام از داده های بالا میتوانیم از مدل زیر استفاده کنیم
fi = rfc.feature_importances_
print(f"feature importances : {fi}")
print(f"sum of feature importances : {fi.sum()}")

feature_importances = pd.Series(data=fi, index=X.columns)
feature_importances=feature_importances.sort_values(ascending=False)
print(f"\vfwature_importances :\n{feature_importances}")

# plt.figure(figsize=(8,6))
# colors = sns.color_palwtte('pasel', len(feature_importances))


feature importances : [0.16069234 0.13414281 0.06653267 0.23538005 0.11159519 0.29165694]
sum of feature importances : 1.0
fwature_importances :
safety      0.291657
persons     0.235380
buying      0.160692
maint       0.134143
lug_boot    0.111595
doors       0.066533
dtype: float64


In [ ]:
# پیدا کردن هاپر
rf = RandomForestClassifier()

params = {
    'n_estimators' : [50, 100,200],
    'max_depth' : [None, 10,15,20],
    'min_samples_split': [2, 5],
    'min_samples_leaf' : [1, 2 ,4],
}

random_search = RandomizedSearchCV(rf, params, n_iter=100, cv=5 , verbose=1, n_jobs=-1, random_state=42)
random_search.fit(X_train, y_train)

print(f"Best parameters : {random_search.best_params_}")
best_rf = random_search.best_wstimator_
y_pred = best_rf.predict(X_test)

print("confusion_matrix:\n", confusion_matrix(y_test, y_pred))
print("sccuracy_score:", accuracy_score(y_test, y_pred))
print("recall_score:", recall_score(y_test, y_pred, average='micro'))
print("precision_score:", precision_score(y_test, y_pred,average='micro'))
print(f"\nClassitication Report:\n{classification_report(y_test, y_pred)}")

Fitting 5 folds for each of 72 candidates, totalling 360 fits


/usr/local/lib/python3.11/dist-packages/sklearn/model_selection/_search.py:317: UserWarning: The total space of parameters 72 is smaller than n_iter=100. Running 72 iterations. For exhaustive searches, use GridSearchCV.
  n_iter = self.n_iter


KeyboardInterrupt: 