<a href="https://colab.research.google.com/github/Artificial-i/-1-5/blob/main/Vedio38_43_T5_Fasl4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive/')

Mounted at /content/drive/


In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split, GridSearchCV,RandomizedSearchCV
from sklearn.metrics import accuracy_score,confusion_matrix,recall_score,classification_report,confusion_matrix
from sklearn.ensemble import RandomForestClassifier
%matplotlib inline

In [4]:
df=pd.read_csv('car_evaluation.csv')
df.head()


vhigh vhigh.1  2 2.1  small   low  unacc
0  vhigh   vhigh  2   2  small   med  unacc
1  vhigh   vhigh  2   2  small  high  unacc
2  vhigh   vhigh  2   2    med   low  unacc
3  vhigh   vhigh  2   2    med   med  unacc
4  vhigh   vhigh  2   2    med  high  unacc

In [ ]:
col_names = ['buying','maint','doors','persons','lug_boot','safety','class']
df.columns = col_names
df.head()

In [ ]:
df.shape
df.columns
df.dtypes
df.info()
df.nunique()
df['buying'].value_counts()
df.isnull().sum()

In [21]:
X = df.drop(['class'], axis=1)
y = df['class']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.33, random_state = 42)

In [ ]:
!pip install category_encoders

In [30]:
import category_encoders as ce

ohe = ce.OneHotEncoder()
X_train_1 = ohe.fit_transform(X_train)
X_test_1 = ohe.transform(X_test)

oe = ce.OrdinalEncoder()
X_train_2 = oe.fit_transform(X_train)
X_test_2 = oe.transform(X_test)

be= ce.BinaryEncoder()
X_train_3 = be.fit_transform(X_train, y_train)
X_test_3 = be.transform(X_test)

/usr/local/lib/python3.11/dist-packages/sklearn/base.py:411: FutureWarning: The `_get_tags` method is deprecated in 1.6 and will be removed in 1.7. Please implement the `__sklearn_tags__` method.
  If False and the attribute exists, then check that it is equal to
/usr/local/lib/python3.11/dist-packages/sklearn/base.py:411: FutureWarning: The `_get_tags` method is deprecated in 1.6 and will be removed in 1.7. Please implement the `__sklearn_tags__` method.
  If False and the attribute exists, then check that it is equal to
/usr/local/lib/python3.11/dist-packages/sklearn/base.py:411: FutureWarning: The `_get_tags` method is deprecated in 1.6 and will be removed in 1.7. Please implement the `__sklearn_tags__` method.
  If False and the attribute exists, then check that it is equal to
/usr/local/lib/python3.11/dist-packages/sklearn/base.py:411: FutureWarning: The `_get_tags` method is deprecated in 1.6 and will be removed in 1.7. Please implement the `__sklearn_tags__` method.
  If False a

In [ ]:
import category_encoders as ce
oe = ce.OrdinalEncoder()
X_train = oe.fit_transform(X_train)
X_test = oe.transform(X_test)
X_train , X_test

In [32]:
rfc = RandomForestClassifier(random_state=0)
rfc.fit(X_train, y_train)
y_pred = rfc.predict(X_test)

print("confusion_matrix:\n",confusion_matrix(y_test, y_pred))
print("accuracy_score:", accuracy_score(y_test, y_pred))
print("recall_score:" , recall_score(y_test, y_pred,average='micro'))
print("precision_score:", precision_score(y_test, y_pred,average='micro'))
print(f"\nClassification Report:\n{classification_report(y_test, y_pred)}")

confusion_matrix:
 [[119   2   5   1]
 [  1  13   2   2]
 [  2   0 397   0]
 [  5   0   0  21]]
accuracy_score: 0.9649122807017544
recall_score: 0.9649122807017544


NameError: name 'precision_score' is not defined

In [28]:
rfc_100 = RandomForestClassifier(n_estimators=5, random_state=0)
rfc_100.fit(X_train, y_train)
y_pred_100 = rfc_100.predict(X_test)

print("confusion_matrix:\n", confusion_matrix(y_test, y_pred_100))
print("accuracy_score:", accuracy_score(y_test, y_pred_100))
print("recall_score:", recall_score(y_test, y_pred_100,average='micro'))
print("precision_score:", precision_score(y_test, y_pred_100,average='micro'))
print(f"\nClassification Report:\n{classification_report(y_test, y_pred_100)}")

confusion_matrix:
 [[110   6  11   0]
 [  2  11   2   3]
 [  8   0 391   0]
 [  5   4   1  16]]
accuracy_score: 0.9263157894736842
recall_score: 0.9263157894736842


NameError: name 'precision_score' is not defined